# Generated by Django 4.2.28 on 2026-02-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('hp', models.PositiveIntegerField(help_text='Horsepower')),
                ('year', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric')], default='diesel', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('rent_price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rent_price_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Under Maintenance'), ('sold', 'Sold')], default='available', max_length=15)),
                ('driver_available', models.BooleanField(default=False)),
                ('driver_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('location', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TractorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tractors/images/')),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.tractor')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
