# Generated by Django 4.2.28 on 2026-02-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('rent_type', models.CharField(choices=[('hourly', 'Per Hour'), ('acre', 'Per Acre'), ('daily', 'Per Day')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Hours or Acres', max_digits=8)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('driver_required', models.BooleanField(default=False)),
                ('driver_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('delivery_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
